from future import standard_library
import ulmo.usgs.nwis as nwis
import pandas as pd


def gcstations():
    gauges = pd.DataFrame.from_records(
        [(0.0,  '09380000', "Colorado River at Lees Ferry"),
         (87.4, '09402500', 'Colorado River near Grand Canyon'),
         (225.0,'09404200', 'Colorado River above Diamond Creek')],
        columns=["RM", "ID", "Name"])
    return gauges


def gcmiles(what='all'):
    camps = [
        # RM    Name                    Type        Side    Size
        (0.0,   "Lee's Ferry",          "Camp",     "R",    "L"),
        (5.0,   "5 Mile",               "Camp",     "R",    "S"),
        (5.9,   "6 Mile",               "Camp",     "R",    "S"),
        (8.1,   "Jackass Creek",        "Camp",     "L",    "L"),
        (8.1,   "Badger Creek",         "Camp",     "R",    "M"),
        (8.8,   "Below Jackass",        "Camp",     "L",    "S"),
        (9.0,   "Sandbar",              "Camp",     "L",    "S"),
        (11.3,  "Soap Creek",           "Camp",     "R",    "M"),
        (12.1,  "Brown's Inscription",  "Camp",     "L",    "S"),
        (12.4,  "12.4 Mile",            "Camp",     "L",    "S"),
        (13.1,  "13 Mile Ledges",       "Camp",     "R",    "M"),
        (14.4,  "Sheer Wall",           "Camp",     "L",    "S"),
        (16.4,  "Hot Na Na",            "Camp",     "L",    "M"),
        (17.3,  "House Rock",           "Camp",     "R",    "L"),
        (18.4,  "18 Mi. Wash",          "Camp",     "L",    "M"),
        (18.5,  "18 Mi. Ledges",        "Camp",     "L",    "S"),
        (19.2,  "19.2 Mi.",             "Camp",     "R",    "S"),
        (19.4,  "19.4 Mile",            "Camp",     "L",    "L"),
        (20.2,  "Twenty Mile",          "Camp",     "L",    "L"),
        (20.7,  "Upper North Canyon",   "Camp",     "R",    "L"),
        (20.8,  "Lower North Canyon",   "Camp",     "R",    "L"),
        (22.1,  "22 Mile",              "Camp",     "R",    "S"),
        (22.7,  "Indian Dick",          "Camp",     "L",    "L"),
        (23.5,  "Lone Cedar",           "Camp",     "L",    "M"),
        (24.5,  "24.5 Mile",            "Camp",     "L",    "M"),
        (26.4,  "Above tiger Wash",     "Camp",     "L",    "S"),
        (29.5,  "Shinumo Wash",         "Camp",     "L",    "L"),
        (29.8,  "Island",               "Camp",     "R",    "S"),
        (30.6,  "Fence Fault",          "Camp",     "R",    "L"),
        (30.8,  "Sand Pile",            "Camp",     "R",    "L"),
        (31.6,  "Upper South Canyon",   "Camp",     "R",    "S"),
        (31.7,  "South Canyon",         "Camp",     "R",    "L"),
        (33.8,  "Below Redwall",        "Camp",     "L",    "S"),
        (34.0,  "Little Redwall",       "Camp",     "L",    "M"),
        (35.1,  "Nautiloid",            "Camp",     "L",    "L"),
        (37.9,  "Tatahatso",            "Camp",     "L",    "L"),
        (38.3,  "Above Martha's",       "Camp",     "L",    "S"),
        (38.7,  "Martha's",             "Camp",     "L",    "M"),
        (39.3,  "Redbud Alcove",        "Camp",     "R",    "L"),
        (41.2,  "Buck Farm",            "Camp",     "R",    "L"),
        (43.4,  "Anasazi Bridge",       "Camp",     "L",    "S"),
        (43.6,  "Lower Anasazi",        "Camp",     "L",    "S"),
        (44.0,  "Pres. Harding",        "Camp",     "L",    "M"),
        (44.5,  "Eminence",             "Camp",     "L",    "L"),
        (45.0,  "Willie Taylor",        "Camp",     "L",    "S"),
        (47.2,  "Duck-n-Quack",         "Camp",     "L",    "S"),
        (47.2,  "Upper Saddle",         "Camp"      "R",    "L"),
        (47.7,  "Lower Saddle",         "Camp",     "R",    "L"),
        (50.1,  "Dinosaur",             "Camp",     "R",    "L"),
        (52.1,  "Little Nankoweap",     "Camp",     "R",    "M"),
        (53.1,  "Upper Nankoweap",      "Camp",     "R",    "L"),
        (53.4,  "Main Nankoweap",       "Camp",     "R",    "L"),
        (53.5,  "Lower Nankoweap",      "Camp",     "R",    "M"),
        (56.6,  "Kwagunt",              "Camp",     "R",    "L"),
        (57.1,  "Below Kwagunt",        "Camp",     "R",    "M"),
        (58.0,  "Malagosa",             "Camp",     "R",    "S"),
        (58.1,  "Opposite Malagosa",    "Camp",     "L",    "M"),
        (58.6,  "Awatubi",              "Camp",     "R",    "M"),
        (59.1,  "Below Awatubi",        "Camp",     "L",    "S"),
        (60.2,  "60 Mile",              "Camp",     "R",    "S"),
        (60.7,  "60 Mile Ledge",        "Camp",     "R",    "S"),
        (61.1,  "61 Mile",              "Camp",     "R",    "S"),
        (61.7,  "Above LCR",            "Camp",     "R",    "M"),
        (62.2,  "Below LCR"             "Camp",     "R",    "S"),
        (63.0,  "Crash Canyon",         "Camp",     "R",    "S"),
        (64.6,  "Carbon Creek",         "Camp",     "R",    "L"),
        (65.9,  "Chuar/Lava Canyon",    "Camp",     "R",    "M"),
        (66.1,  "Palisades",            "Camp",     "L",    "M"),
        (66.8,  "Espejo",               "Camp",     "L",    "S"),
        (67.7,  "Comanche",             "Camp",     "L",    "S"),
        (68.3,  "Upper Tanner",         "Camp",     "R",    "L"),
        (68.7,  "Tanner",               "Camp",     "R",    "L"),
        (69.3,  "Below Tanner Rapid",   "Camp",     "L",    "M"),
        (70.1,  "Basalt",               "Camp",     "R",    "M"),
        (71.2,  "Cardenas",             "Camp",     "L",    "M"),
        (72.4,  "Upper Unkar",          "Camp",     "R",    "M"),
        (72.7,  "Unkar Left",           "Camp",     "L",    "L"),
        (74.2,  "Anasazi Granary",      "Camp"      "L",    "S"),
        (74.6,  "Upper Rattlesnake",    "Camp",     "R",    "L"),
        (75.4,  "Escalante",            "Camp",     "L",    "S"),
        (75.7,  "Upper Nevills",        "Camp",     "L",    "S"),
        (76.1,  "Nevills",              "Camp",     "L",    "L"),
        (76.5,  "Below Nevills",        "Camp",     "R",    "M"),
        (76.5,  "Papago",               "Camp",     "L",    "M"),
        (77.1,  "Hance",                "Camp",     "L",    "M"),
        (79.4,  "Below Sockdolager",    "Camp",     "L",    "S"),
        (81.7,  "Grapevine",            "Camp",     "L",    "L"),
        (84.6,  "Clear Creek",          "Camp",     "R",    "S"),
        (84.8,  "Below Clear Creek",    "Camp",     "R",    "S"),
        (85.0,  "Zoroaster",            "Camp",     "L",    "M"),
        (87.6,  "Upper Cremation",      "Camp",     "L",    "M"),
        (87.8,  "Lower Cremation",      "Camp",     "L",    "M"),
        (89.9,  "Pipe Creek",           "Camp",     "R",    "S"),
        (91.7,  "91 Mile Creek",        "Camp",     "L",    "S"),
        (92.1,  "Trinity Creek",        "Camp",     "R",    "S"),
        (92.8,  "Above Salt Creek",     "Camp",     "L",    "M"),
        (93.2,  "Salt Creek",           "Camp",     "L",    "S"),
        (93.8,  "Granite",              "Camp",     "L",    "L"),
        (94.8,  "94 Mile Canyon",       "Camp",     "R",    "S"),
        (95.2,  "Hermit",               "Camp",     "L",    "M"),
        (96.5,  "Schist",               "Camp",     "L",    "M"),
        (97.2,  "Boucher",              "Camp",     "L",    "M"),
        (98.7,  "Crystal",              "Camp",     "R",    "M"),
        (98.9,  "Ego Beach",            "Camp",     "R",    "S"),
        (99.7,  "Willies Necktie",      "Camp",     "L",    "S"),
        (100.1, "Lower Tuna",           "Camp",     "L",    "L"),
        (103.4, "New Shady Grove",      "Camp",     "R",    "M"),
        (103.7, "103 Mile",             "Camp",     "R",    "M"),
        (104.4, "Emerald",              "Camp",     "R",    "M"),
        (108.7, "Hotauta",              "Camp"      "R",    "M"),
        (108.3, "Ross Wheeler",         "Camp",     "L",    "S"),
        (108.5, "Parkins Inscription",  "Camp",     "R",    "S"),
        (108.9, "Bass Crossing",        "Camp",     "R",    "R"),
        (109.0, "Bass",                 "Camp",     "R",    "L"),
        (110.0, "110 Mile",             "Camp",     "R",    "L"),
        (112.8, "Waltenberg",           "Camp",     "R",    "S"),
        (114.9, "Upper Garnet",         "Camp",     "R",    "M"),
        (115.1, "LowerGarnet",          "Camp",     "R",    "M"),
        (117.6, "Buckhorn Canyon",      "Camp",     "L",    "S"),
        (118.3, "Below Elves Right",    "Camp",     "R",    "S"),
        (119.1, "119 Mile",             "Camp",     "R",    "S"),
        (119.4, "Big Dune",             "Camp",     "R",    "M"),
        (119.9, "119.8 Mile",           "Camp",     "R",    "S"),
        (120.3, "120 Mile",             "Camp",     "L",    "L"),
        (120.6, "Blacktail",            "Camp",     "R",    "M"),
        (120.6, "Opposite Blacktail",   "Camp",     "L",    "S"),
        (120.7, "Lower Blacktail",      "Camp",     "R",    "M"),
        (120.8, "Below Blacktail",      "Camp",     "L",    "L"),
        (121.4, "121.4 Mile",           "Camp",     "L",    "S"),
        (122.3, "122.3 Mile",           "Camp",     "L",    "S"),
        (122.8, "122 Mile Canyon",      "Camp",     "L",    "L"),
        (123.2, "Upper Forster",        "Camp",     "L",    "M"),
        (123.6, "Below Forster",        "Camp",     "R",    "M"),
        (124.2, "Enfilade",             "Camp",     "L",    "M"),
        (125.5, "Fossil",               "Camp",     "L",    "L"),
        (126.1, "Below Fossil",         "Camp",     "L",    "M"),
        (127.0, "Randys Rock",          "Camp",     "R",    "L"),
        (131.7, "Below Bedrock",        "Camp",     "R",    "L"),
        (132.2, "Galloway",             "Camp",     "R",    "M"),
        (132.5, "Stone Creek",          "Camp",     "R",    "L"),
        (133.7, "Talking Heads",        "Camp",     "L",    "M"),
        (134.2, "Racetrack",            "Camp",     "R",    "M"),
        (134.4, "Lower Tapeats",        "Camp",     "R",    "M"),
        (134.8, "Above Owl Eyes",       "Camp",     "L",    "L"),
        (135.2, "Owl Eyes",             "Camp",     "L",    "L"),
        (136.6, "Junebug",              "Camp",     "L",    "S"),
        (136.8, "Across Deer Creek",    "Camp",     "L",    "M"),
        (137.1, "OC's",                 "Camp",     "L",    "L"),
        (137.6, "Pancho's Kitchen",     "Camp",     "L",    "L"),
        (137.7, "Football Field",       "Camp",     "L",    "L"),
        (137.8, "Backeddy",             "Camp",     "L",    "L"),
        (138.6, "Doris",                "Camp",     "L",    "M"),
        (139.1, "139 Mile",             "Camp",     "L",    "S"),
        (139.6, "Fishtail",             "Camp",     "R",    "S"),
        (140.4, "Keyhole",              "Camp",     "L",    "M"),
        (143.9, "Above Kanab",          "Camp",     "L",    "S"),
        (144.8, "Below Kanab",          "Camp",     "R",    "M"),
        (145.9, "Above Olo",            "Camp",     "L",    "L"),
        (146.1, "Olo",                  "Camp",     "L",    "S"),
        (148.4, "Opposite Matkat",      "Camp",     "R",    "S"),
        (148.9, "Matkat Hotel",         "Camp",     "L",    "M"),
        (150.3, "Patch",                "Camp",     "R",    "M"),
        (150.7, "Upsey Hotel",          "Camp",     "L",    "S"),
        (151.9, "Upper Ledges",         "Camp",     "R",    "M"),
        (152.1, "Ledges",               "Camp",     "R",    "M"),
        (156.3, "Last Chance",          "Camp",     "R",    "M"),
        (156.9, "Very Last Chance",     "Camp",     "R",    "S"),
        (158.3, "First Chance",         "Camp",     "R",    "S"),
        (158.7, "158.7 Mile",           "Camp",     "R",    "M"),
        (159.2, "Second Chance",        "Camp",     "R",    "S"),
        (160.5, "160.5 Mile",           "Camp",     "L",    "S"),
        (161.3, "161.3 Mile",           "Camp",     "R",    "M"),
        (165.1, "Above Tuckup",         "Camp",     "R",    "S"),
        (165.2, "Tuckup",               "Camp",     "R",    "L"),
        (165.4, "Below Tuckup",         "Camp",     "L",    "S"),
        (165.7, "167.5 Mile",           "Camp",     "R",    "S"),
        (167.0, "Upper National",       "Camp",     "L",    "L"),
        (167.1, "Lower National",       "Camp",     "L",    "L"),
        (167.5, "Below National",       "Camp",     "L",    "S"),
        (168.8, "Fern Glen",            "Camp",     "R",    "L"),
        (171.6, "Stairway Canyon",      "Camp",     "R",    "M"),
        (172.1, "Mohawk",               "Camp",     "L",    "L"),
        (172.6, "172.6 Mile",           "Camp",     "L",    "S"),
        (174.7, "Upper Cove",           "Camp",     "R",    "M"),
        (174.8, "Lower Cover",          "Camp",     "R",    "L"),
        (176.3, "Below Red Slide",      "Camp",     "L",    "L"),
        (177.6, "Honga Spring",         "Camp",     "L",    "M"),
        (178.1, "Above Anvil",          "Camp",     "L",    "L"),
        (179.5, "Above Lava",           "Camp",     "L",    "M"),
        (180.1, "Below Lower Lava",     "Camp",     "R",    "L"),
        (182.8, "Upper Chevron",        "Camp",     "R",    "L"),
        (182.9, "Lower Chevron",        "Camp",     "R",    "M"),
        (183.3, "183.3 Mile",           "Camp",     "L",    "M"),
        (184.9, "184.9 Mile",           "Camp",     "L",    "S"),
        (185.9, "Upper 185 Mile",       "Camp",     "R",    "L"),
        (186.0, "Lower 185 Mile",       "Camp",     "R",    "L"),
        (186.4, "186.4 Mile",           "Camp",     "L",    "L"),
        (187.5, "Whitmore Helipad",     "Camp",     "L",    "M"),
        (188.4, "Whitmore Wash",        "Camp",     "R",    "L"),
        (188.7, "Lower Whitmore",       "Camp",     "R",    "L"),
        (190.4, "Granite Island",       "Camp",     "R",    "S"),
        (190.7, "190.7 Mile",           "Camp",     "L",    "S"),
        (191.5, "Upper Fat City",       "Camp",     "R",    "M"),
        (192.3, "Fat City",             "Camp",     "L",    "L"),
        (193.3, "193.3 Mile",           "Camp",     "R",    "S"),
        (194.6, "Hualapai Acres",       "Camp",     "L",    "L"),
        (196.9, "Froggy Fault",         "Camp",     "L",    "M"),
        (197.0, "Below Froggy",         "Camp",     "L",    "S"),
        (198.9, "Parashant",            "Camp",     "R",    "M"),
        (199.3, "Below Parashant",      "Camp",     "R",    "M"),
        (202.3, "202 Mile",             "Camp",     "R",    "M"),
        (202.9, "203 Mile",             "Camp",     "R",    "M"),
        (204.9, "Below Spring Canyon",  "Camp",     "R",    "S"),
        (205.7, "205 Mile",             "Camp",     "L",    "S"),
        (207.0, "Indian Canyon",        "Camp",     "R",    "M"),
        (207.9, "207.9 Mile",           "Camp",     "L",    "S"),
        (209.1, "Granite Park",         "Camp",     "L",    "L"),
        (209.8, "209.8 Mile",           "Camp",     "R",    "L"),
        (210.2, "210.2 Mile",           "Camp",     "R",    "L"),
        (211.9, "Upper Fall Canyon",    "Camp",     "R",    "M"),
        (212.0, "Lower Fall Canyon",    "Camp",     "R",    "S"),
        (213.1, "213.1 Mile",           "Camp",     "R",    "S"),
        (213.3, "Pumpkin Spring",       "Camp",     "L",    "L"),
        (214.5, "214 Mile",             "Camp",     "R",    "M"),
        (216.1, "Opposite 3 Springs",   "Camp",     "R",    "L"),
        (218.0, "217 Mile Rapid",       "Camp",     "L",    "M"),
        (220.0, "Upper 220 Mile",       "Camp",     "R",    "L"),
        (220.1, "Middle 220 Mile",      "Camp",     "R",    "M"),
        (220.2, "Lower 220 Mile",       "Camp",     "R",    "M"),
        (221.6, "221 Mile",             "Camp",     "R",    "L"),
        (222.2, "222 Mile",             "Camp",     "L",    "L"),
        (223.7, "224 Mile",             "Camp",     "L",    "M"),
        (224.9, "224.9 Mile",           "Camp",     "L",    "M"),
        (225.7, "Last Chance Diamond",  "Camp",     "R",    "S"),
        (226.3, "Truck Seat",           "Camp",     "R",    "M"),
        (227.3, "227.3 Mile",           "Camp",     "R",    "M"),
        (229.3, "Travertine Canyon",    "Camp",     "L",    "M"),
        (230.6, "Travertine Falls",     "Camp",     "L",    "M"),
        (231.0, "231 Mile",             "Camp",     "R",    "M"),
        (234.4, "234.4 Mile",           "Camp",     "R",    "M"),
        (235.3, "235.1 Mile",           "Camp",     "L",    "M"),
        (236.1, "Gneiss Canyon",        "Camp",     "R",    "M"),
        (236.7, "236.7 Mile",           "Camp",     "L",    "M"),
        (238.7, "Bridge City",          "Camp",     "L",    "M"),
        (239.8, "Separation Canyon",    "Camp",     "R",    "M"),
        (242.7, "242.7 Mile",           "Camp",     "R",    "M"),
        (243.0, "243 Mile",             "Camp",     "R",    "M"),
        (246.2, "Spenser Canyon",       "Camp",     "L",    "M"),
        (248.7, "Surprise Canyon",      "Camp",     "R",    "M"),
        (250.0, "Tomahawk",             "Camp",     "R",    "M"),
        (260.7, "Lower Quartermaster",  "Camp",     "L",    "M"),
        (264.6, "Dry Canyon",           "Camp",     "R",    "M"),
        (273.6, "273.6 Mile",           "Camp",     "L",    "M"),
        (279.4, "279.4 Mile",           "Camp",     "L",    "M"),
        (280.0, "280 Mile (Last Chance)","Camp",    "R",    "M")
    ]

    poi = [
        (0.0,   "Lee's Ferry",          "Access",   "R"),
        (12.1,  "Browns Inscription",   "Hike",     "L"),
        (31.9,  "Vaseys Paradise",      "Water",    "R"),
        (53.2,  "Nankoweap Creek",      "Water",    "R"),
        (53.3,  "Nankoweap Day Use",    "Hike",     "R"),
        (61.9,  "Little Colorado",      "Hike",     "L"),
        (66.1,  "Palisade Creek",       "Water",    "R"),
        (88.2,  "Phantom Ranch",        "Access",   "R"),
        (93.9,  "Monument Creek",       "Water",    "L"),
        (95.2,  "Hermit Creek",         "Water",    "L"),
        (98.9,  "Ego Beach",            "Water",    "R"),
        (109.2, "Shinumo Creek",        "Water",    "R"),
        (116.5, "Elves Chasm",          "Water",    "L"),
        (120.6, "Blacktail Creek",      "Water",    "R"),
        (134.3, "Tapeats Creek",        "Water",    "R"),
        (136.9, "Deer Creek",           "Water",    "R"),
        (144.0, "Kanab Creek",          "Water",    "R"),
        (148.5, "Matkatimiba Canyon",   "Water",    "L"),
        (225.7, "Diamond Creek",        "Access",   "L")
    ]
    rapids = [
    #   RM      Name                    Feature     Rating(s)
        (0.2,   "Paria Riffle",         "Rapid",    1,  1,  1,  1),
        (2.8,   "Cathedral Wash",       "Rapid",    2,  2,  2,  2),
        (7.8,   "Badger Creek",         "Rapid",    5,  5,  6,  6),
        (7.8,   "Badger Creek",         "Rapid",    8,  7,  6,  5),
        (11.2,  "Soap Creek",           "Rapid",    6,  5,  5,  5),
        (12.8,  "Thirteen Mile",        "Rapid",    1,  1,  1,  1),
        (14.5,  "Sheer Wall",           "Rapid",    5,  4,  3,  2),
        (17.1,  "House Rock",           "Rapid",    9,  8,  7,  7),
        (17.4,  "Redneck",              "Rapid",    3,  3,  3,  3),
        (20.5,  "North Canyon",         "Rapid",    4,  4,  5,  5),
        (21.2,  "21 Mile",              "Rapid",    5,  5,  5,  5),
        (23.0,  "23 Mile",              "Rapid",    6,  5,  5,  4),
        (23.5,  "23.5 Mile",            "Rapid",    4,  4,  4,  4),
        (24.1,  "Georgie (24 Mi.)",     "Rapid",    8,  7,  6,  6),
        (24.5,  "24.5 Mile",            "Rapid",    6,  6,  5,  5),
        (24.9,  "25 Mile",              "Rapid",    7,  6,  5,  5),
        (25.5,  "Cave Springs",         "Rapid",    6,  5,  5,  6),
        (25.8,  "26 Mile",              "Rapid",    3,  3,  3,  3),
        (26.7,  "Tiger Wash",           "Rapid",    5,  4,  4,  4),
        (26.9,  "MNA",                  "Rapid",    4,  3,  1,  0),
        (29.2,  "29 Mile",              "Rapid",    3,  3,  3,  3),
        (36.0,  "36 Mile",              "Rapid",    4,  3,  3,  3),
        (43.7,  "Pres. Harding",        "Rapid",    4,  4,  4,  4),
        (52.2,  "Nankoweap",            "Rapid",    3,  3,  4,  4),
        (55.9,  "Kwagunt",              "Rapid",    6,  6,  6,  6),
        (59.7,  "60 Mile",              "Rapid",    4,  4,  4,  4),
        (65.5,  "Chuar",                "Rapid",    4,  3,  4,  5),
        (68.4,  "Tanner",               "Rapid",    4,  4,  4,  4),
        (72.4,  "Unkar",                "Rapid",    7,  7,  6,  6),
        (75.3,  "Nevills",              "Rapid",    6,  6,  6,  6),
        (76.7,  "Hance",                "Rapid",    9,  8,  7,  7),
        (78.5,  "Sockdolager",          "Rapid",    8,  8,  9,  9),
        (81.4,  "Grapevine",            "Rapid",    8,  8,  8,  8),
        (83.5,  "83 Mile",              "Rapid",    6,  5,  4,  3),
        (84.7,  "Zoroaster",            "Rapid",    8,  7,  6,  5),
        (85.2,  "85 Mile",              "Rapid",    5,  4,  4,  3),
        (87.9,  "Bright Angel",         "Rapid",    4,  4,  4,  4),
        (90.3,  "Horn Creek",           "Rapid",    9, 10,  8,  8),
        (93.4,  "Granite",              "Rapid",    8,  8,  9,  9),
        (94.8,  "Hermit",               "Rapid",    9,  8,  9,  9),
        (96.5,  "Boucher",              "Rapid",    5,  4,  4,  3),
        (98.1,  "Crystal",              "Rapid",   10,  8,  9, 10),
        (99.1,  "Tuna Creek",           "Rapid",    5,  5,  6,  6),
        (99.5,  "Lower Tuna",           "Rapid",    4,  4,  4,  4),
        (100.0, "Nixon Rock",           "Rapid",    5,  5,  5,  5),
        (100.5, "Agate",                "Rapid",    2,  3,  3,  4),
        (101.1, "Sapphire",             "Rapid",    7,  7,  7,  7),
        (101.9, "Turquoise",            "Rapid",    6,  5,  4,  3),
        (103.8, "104 Mi./Emerald",      "Rapid",    7,  6,  6,  5),
        (104.6, "Ruby",                 "Rapid",    7,  6,  6,  7),
        (105.9, "Serpentine",           "Rapid",    8,  7,  7,  6),
        (107.8, "Bass",                 "Rapid",    6,  5,  4,  3),
        (108.6, "Shinumo",              "Rapid",    4,  4,  5,  5),
        (109.8, "110 Mile",             "Rapid",    4,  3,  1,  0),
        (110.7, "Hakatai",              "Rapid",    4,  4,  4,  4),
        (112.2, "Waltenberg",           "Rapid",    9,  8,  7,  6),
        (112.5, "112 & 1/2 Mile",       "Rapid",    6,  4,  2,  1),
        (113.0, "Rancid Tuna",          "Rapid",    6,  6,  6,  6),
        (118.8, "119 Mile",             "Rapid",    4,  3,  2,  1),
        (120.6, "Blacktail",            "Rapid",    3,  3,  3,  3),
        (122.2, "122 Mile",             "Rapid",    4,  4,  5,  6),
        (123.3, "Forster",              "Rapid",    6,  6,  6,  6),
        (125.5, "Fossil",               "Rapid",    6,  7,  6,  6),
        (127.5, "127 Mile",             "Rapid",    4,  4,  3,  2),
        (129.2, "128 Mile",             "Rapid",    5,  5,  5,  5),
        (129.7, "Specter",              "Rapid",    8,  7,  6,  5),
        (131.1, "Bedrock",              "Rapid",    8,  8,  8,  8),
        (132.3, "Deubendorff",          "Rapid",    9,  8,  8,  7),
        (134.4, "Tapeats",              "Rapid",    8,  7,  6,  5),
        (135.4, "Helicopter Eddy",      "Rapid",    3,  3,  3,  3),
        (138.4, "Doris",                "Rapid",    5,  6,  6,  7),
        (139.2, "138.5 Mile",           "Rapid",    4,  4,  4,  4),
        (139.7, "Fishtale",             "Rapid",    7,  6,  6,  5),
        (141.7, "141 Mile",             "Rapid",    2,  2,  2,  2),
        (144.0, "Kanab",                "Rapid",    4,  3,  3,  3),
        (148.4, "Matkatimiba",          "Rapid",    2,  2,  2,  2),
        (150.2, "Upset",                "Rapid",    9,  8,  8,  6),
        (154.0, "Sinyala",              "Rapid",    2,  2,  2,  2),
        (165.0, "164 Mile",             "Rapid",    3,  3,  3,  3),
        (167.0, "National",             "Rapid",    2,  2,  2,  2),
        (168.5, "Fern Glen",            "Rapid",    3,  3,  3,  3),
        (171.9, "Gateway",              "Rapid",    3,  3,  3,  3),
        (179.7, "Lava Falls",           "Rapid",   10, 10, 10, 10),
        (180.1, "Lower Lava",           "Rapid",    5,  5,  5,  5),
        (186.0, "185 Mile",             "Rapid",    2,  2,  2,  2),
        (188.3, "Whitmore",             "Rapid",    3,  3,  3,  3),
        (205.6, "205 Mile/Kolb",        "Rapid",    8,  7,  7,  6),
        (209.2, "209 Mile",             "Rapid",    7,  7,  7,  7),
        (212.5, "Little Bastard",       "Rapid",    7,  5,  3,  1),
        (216.0, "Three Springs",        "Rapid",    2,  2,  2,  2),
        (217.8, "217 Mile",             "Rapid",    4,  4,  5,  4),
        (220.7, "Granite Springs",      "Rapid",    2,  2,  2,  2),
        (223.7, "224 Mile",             "Rapid",    2,  3,  3,  4),
        (225.9, "Diamond Creek",        "Rapid",    4,  4,  4,  4),
        (229.3, "Travertine",           "Rapid",    2,  2,  2,  2),
        (231.2, "231 Mile",             "Rapid",    7,  6,  5,  4),
        (232.5, "Killer Fang Falls",    "Rapid",    7,  6,  5,  4),
        (233.9, "234 Mile",             "Rapid",    6,  5,  4,  4),
        (235.3, "Bridge Canyon",        "Rapid",    6,  5,  4,  3),
        (236.0, "Gneiss Canyon",        "Rapid",    6,  5,  4,  3),
        (280.8, "Pearce Ferry",         "Rapid",   10, 10, 10, 10)
    ]
    print(type(rapids))
    gcr = pd.DataFrame.from_records(rapids,
                                    columns=['RM','Name','Type',
                                             'VeryLow','Low','Medium','High'])
    return gcr


def get_flows(start_date):
    if start_date is None:
        raise ValueError("Start date cannot be None.")

    stations = gcstations()
    print(stations['ID'])



if __name__ == '__main__':
    print("in gctides")
    get_flows("04/23/1992")
    print(gcmiles())
